### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by hdfhdfhdfhfddfdf** [andrerahardjo97/discord-sticky-message-bot#62]
**I get This Error from the command prompt**

C:\Users\eimaa\dcstick\node_modules\discord.js\src\client\Client.js:548
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\eimaa\dcstick\node_modules\discord.js\src\client\Client.js:548:13)
    at new Client (C:\Users\eimaa\dcstick\node_modules\discord.js\src\client\Client.js:76:10)
    at Object.<anonymous> (C:\Users\eimaa\dcstick\index.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'

**Comment by just-rich** [comment]
replace this

const client = new Discord.Client({
  ws: {
    intents: [
      "GUILDS",
      "GUILD_MESSAGES",
    ],
  },
});

with this

const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] })



in the index.js file, youll see it at the top
